# -*- coding: utf-8 -*-
"""2.django 2nd project. Phase 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eMWEy7NiZNy0Ar3oKHxcjN53C4Bjfz8d

# Using Jupyter Notebooks
:label:`sec_jupyter`


This section describes how to edit and run the code
in each section of this book
using the Jupyter Notebook. Make sure you have
installed Jupyter and downloaded the
code as described in
:ref:`chap_installation`.
If you want to know more about Jupyter see the excellent tutorial in
their [documentation](https://jupyter.readthedocs.io/en/latest/).


## Editing and Running the Code Locally

Suppose that the local path of the book's code is `xx/yy/d2l-en/`. Use the shell to change the directory to this path (`cd xx/yy/d2l-en`) and run the command `jupyter notebook`. If your browser does not do this automatically, open http://localhost:8888 and you will see the interface of Jupyter and all the folders containing the code of the book, as shown in :numref:`fig_jupyter00`.

![The folders containing the code of this book.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter00.png?raw=1)
:width:`600px`
:label:`fig_jupyter00`


You can access the notebook files by clicking on the folder displayed on the webpage.
They usually have the suffix ".ipynb".
For the sake of brevity, we create a temporary "test.ipynb" file.
The content displayed after you click it is
shown in :numref:`fig_jupyter01`.
This notebook includes a markdown cell and a code cell. The content in the markdown cell includes "This Is a Title" and "This is text.".
The code cell contains two lines of Python code.

![Markdown and code cells in the "text.ipynb" file.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter01.png?raw=1)
:width:`600px`
:label:`fig_jupyter01`


Double click on the markdown cell to enter edit mode.
Add a new text string "Hello world." at the end of the cell, as shown in :numref:`fig_jupyter02`.

![Edit the markdown cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter02.png?raw=1)
:width:`600px`
:label:`fig_jupyter02`


As demonstrated in :numref:`fig_jupyter03`,
click "Cell" $\rightarrow$ "Run Cells" in the menu bar to run the edited cell.

![Run the cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter03.png?raw=1)
:width:`600px`
:label:`fig_jupyter03`

After running, the markdown cell is shown in :numref:`fig_jupyter04`.

![The markdown cell after running.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter04.png?raw=1)
:width:`600px`
:label:`fig_jupyter04`


Next, click on the code cell. Multiply the elements by 2 after the last line of code, as shown in :numref:`fig_jupyter05`.

![Edit the code cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter05.png?raw=1)
:width:`600px`
:label:`fig_jupyter05`


You can also run the cell with a shortcut ("Ctrl + Enter" by default) and obtain the output result from :numref:`fig_jupyter06`.

![Run the code cell to obtain the output.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter06.png?raw=1)
:width:`600px`
:label:`fig_jupyter06`


When a notebook contains more cells, we can click "Kernel" $\rightarrow$ "Restart & Run All" in the menu bar to run all the cells in the entire notebook. By clicking "Help" $\rightarrow$ "Edit Keyboard Shortcuts" in the menu bar, you can edit the shortcuts according to your preferences.

## Advanced Options

Beyond local editing two things are quite important: editing the notebooks in the markdown format and running Jupyter remotely.
The latter matters when we want to run the code on a faster server.
The former matters since Jupyter's native ipynb format stores a lot of auxiliary data that is
irrelevant to the content,
mostly related to how and where the code is run.
This is confusing for Git, making
reviewing contributions very difficult.
Fortunately there is an alternative---native editing in the markdown format.

### Markdown Files in Jupyter

If you wish to contribute to the content of this book, you need to modify the
source file (md file, not ipynb file) on GitHub.
Using the notedown plugin we
can modify notebooks in the md format directly in Jupyter.


First, install the notedown plugin, run the Jupyter Notebook, and load the plugin:

```
pip install d2l-notedown  # You may need to uninstall the original notedown.
jupyter notebook --NotebookApp.contents_manager_class='notedown.NotedownContentsManager'
```

You may also turn on the notedown plugin by default whenever you run the Jupyter Notebook.
First, generate a Jupyter Notebook configuration file (if it has already been generated, you can skip this step).

```
jupyter notebook --generate-config
```

Then, add the following line to the end of the Jupyter Notebook configuration file (for Linux or macOS, usually in the path `~/.jupyter/jupyter_notebook_config.py`):

```
c.NotebookApp.contents_manager_class = 'notedown.NotedownContentsManager'
```

After that, you only need to run the `jupyter notebook` command to turn on the notedown plugin by default.

### Running Jupyter Notebooks on a Remote Server

Sometimes, you may want to run Jupyter notebooks on a remote server and access it through a browser on your local computer. If Linux or macOS is installed on your local machine (Windows can also support this function through third-party software such as PuTTY), you can use port forwarding:

```
ssh myserver -L 8888:localhost:8888
```

The above string `myserver` is the address of the remote server.
Then we can use http://localhost:8888 to access the remote server `myserver` that runs Jupyter notebooks. We will detail on how to run Jupyter notebooks on AWS instances
later in this appendix.

### Timing

We can use the `ExecuteTime` plugin to time the execution of each code cell in Jupyter notebooks.
Use the following commands to install the plugin:

```
pip install jupyter_contrib_nbextensions
jupyter contrib nbextension install --user
jupyter nbextension enable execute_time/ExecuteTime
```

## Summary

* Using the Jupyter Notebook tool, we can edit, run, and contribute to each section of the book.
* We can run Jupyter notebooks on remote servers using port forwarding.


## Exercises

1. Edit and run the code in this book with the Jupyter Notebook on your local machine.
1. Edit and run the code in this book with the Jupyter Notebook *remotely* via port forwarding.
1. Compare the running time of the operations $\mathbf{A}^\top \mathbf{B}$ and $\mathbf{A} \mathbf{B}$ for two square matrices in $\mathbb{R}^{1024 \times 1024}$. Which one is faster?


[Discussions](https://discuss.d2l.ai/t/421)
"""

# Chunk 1: install Django and create directories + files
!pip install django --quiet

import os

# Create standalone folder structure
os.makedirs('standalone_phase3/templates/home', exist_ok=True)
os.makedirs('standalone_phase3/static/home', exist_ok=True)

# Show folder created
print("Created folders:")
!ls -R standalone_phase3

# Commented out IPython magic to ensure Python compatibility.
# # Chunk 2: write a Django template file (hello.html)
# %%writefile standalone_phase3/templates/home/hello.html
# <!DOCTYPE html>
# <html>
# <head>
#     <meta charset="utf-8">
#     <title>Standalone Django Template Demo</title>
#     <!-- we use {{ static_url }} because we are not using a full Django project with STATIC config -->
#     <link rel="stylesheet" href="{{ static_url }}">
#     <style>
#       /* fallback inline styles for Colab preview if css file not served */
#       body { font-family: Arial, sans-serif; background: #f8fafc; text-align:center; padding: 30px; }
#       h1 { color: #2563eb; margin-bottom: 6px; }
#       p  { color: #374151; }
#     </style>
# </head>
# <body>
#     <h1>Hello {{ name }} 👋</h1>
#     <p>This HTML is rendered by Django's standalone Engine from a template file.</p>
#     <p>CSS link: <code>{{ static_url }}</code></p>
# </body>
# </html>
#

# Commented out IPython magic to ensure Python compatibility.
# # Chunk 3: write a CSS file into static directory
# %%writefile standalone_phase3/static/home/style.css
# /* standalone static css file for the template demo */
# body { background-color: #eef2ff; font-family: Verdana, sans-serif; }
# h1 { color: #1d4ed8; }
# p { color: #374151; }
#

# Chunk 4: render hello.html using Django's standalone template Engine
from django.template import Engine, Context
from django.template.loaders import filesystem
import os

# Point the engine to the templates directory we created
templates_dir = os.path.join(os.getcwd(), 'standalone_phase3', 'templates')
engine = Engine(dirs=[templates_dir])

# Load template by path relative to templates_dir
template = engine.get_template('home/hello.html')

# Provide context variables: name and a static_url (we simulate static path)
context = Context({
    'name': 'Aditya from IIIT Vadodara',
    'static_url': '/static/home/style.css'  # just a path string for demonstration
})

rendered_html = template.render(context)

# Print a short header and the rendered html
print("=== Rendered HTML Output ===\n")
print(rendered_html)
print("\n=== End of Rendered HTML ===\n")

# Show the static file exists and print its path & first few bytes
static_path = os.path.join('standalone_phase3','static','home','style.css')
print("Static file exists:", os.path.exists(static_path))
print("Static file path:", static_path)
print("--- CSS file preview ---")
print(open(static_path, 'r').read().strip()[:200])